### PR TITLE
Capture failed mappings

### LINKED ISSUE #615: Capture failed mappings as span events
We need to keep a track of what types are failing mapping most frequently so that we can imporve the support for our terraform mappings and the sources in general. This should be implemented as a span event on whatever span is active, probably the terraform mapping one if there is one.

It will end up looking somewhat like this:

```go
trace.SpanFromContext(ctx).AddEvent("unmapped resource", trace.WithAttributes(...)
```

### PR DESCRIPTION
**Pull request by dylanratcliffe**
Fixes #615

### CODE REVIEW

File: tfutils/plan_mapper.go [hunk 1]
```diff
@@ -215,6 +235,20 @@ func MappedItemDiffsFromPlan(ctx context.Context, planJson []byte, fileName stri
...
 	}
 
+	// Attach failed mappings to the span
+	for _, result := range results.Results {
+		switch result.Status {
+		case MapStatusUnsupported, MapStatusNotEnoughInfo:
+			span.AddEvent("UnmappedResource", trace.WithAttributes(
+				attribute.String("status", result.Status.String()),
+				attribute.String("message", result.Message),
+				attribute.String("terraform-name", result.TerraformName),
```
Comment (DavidS-ovm) [inline tfutils/plan_mapper.go:245]:
```suggestion
				attribute.String("ovm.climap.status", result.Status.String()),
				attribute.String("ovm.climap.message", result.Message),
				attribute.String("ovm.climap.terraform-name", result.TerraformName),
```

always use the ovm prefix to make the attributes easier to locate in honeycomb

**Review by DavidS-ovm — APPROVED** [review]
That'll work for now. Eventually we'll probably want to change that into a metric, or at least aggregate unmapped resources with the same type into a single event to save on honeycomb costs.
